### ISSUE TITLE
Device-side assert crash during GRPO training on single A6000 (Qwen2) — fails at same point scaled by gradient accumulation

### ISSUE THREAD

**Issue by nick11roberts** [shangshang-wang/Tina#10]
Hi! I’m encountering a repeatable crash when running the default STILL training recipe from Tina on a single A6000 (48 GB) setup (`post_train_model_grpo.sh`). 

### Summary:
Training runs fine until ~16 min 23 s, then crashes with device-side assert triggered during torch.multinomial in generate.
Increasing gradient_accumulation_steps from 4 to 8 delays the crash to ~32 min 56 s (almost exactly 2× longer).
Seems correlated with eval prompts during training (eval_prompt in callback.py).

### Environment:
GPU: NVIDIA RTX A6000 48 GB (single card)
CUDA: 11.8
PyTorch: 2.5.1+cu118
Transformers: 4.55.0
Tina commit: c6274cd
Command run: `./scripts/train/post_train_model_grpo.sh`
Changes from default: gradient_accumulation_steps=8 in config

### Error trace (last part):
```
RuntimeError: CUDA error: device-side assert triggered
...
next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
```

### Observations:
The doubling of crash time with doubled grad accumulation suggests it might be data-dependent (e.g., certain eval prompt triggers NaN/inf in logits or probs < 0). Warning before crash: Caching is incompatible with gradient checkpointing in Qwen2DecoderLayer.

### Question:
Have you seen this with single-GPU setups? Any recommended tweaks for avoiding it during GRPO with Qwen2 on STILL?
Thanks!

### Full trace: 

```
{'loss': 0.0, 'grad_norm': 1.0, 'learning_rate': 1.0666666666666666e-08, 'rewards/len_reward
': 0.0, 'rewards/accuracy_reward': 0.0, 'reward': 0.0, 'reward_std': 0.0, 'completion_length
': 3584.0, 'kl': nan, 'epoch': 0.0}                                                         
  0%|                                                 | 9/7500 [32:56<461:19:28, 221.70s/it]
[WARNING|modeling_layers.py:91] 2025-08-14 00:45:41,044 >> Caching is incompatible with grad
ient checkpointing in Qwen2DecoderLayer. Setting `past_key_value=None`.                     
../aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0]
, thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0`
 failed.                                                                                    
Traceback (most recent call last):                                                          
  File "/home/nick11roberts/github.com/shangshang-wang/Tina/./tina/post_train_hf/grpo.py", l
ine 264, in <module>                                                                        
    main()                                                                                  
  File "/home/nick11roberts/github.com/shangshang-wang/Tina/./tina/post_train_hf/grpo.py", l
ine 252, in main                                                                            
    train_result = trainer.train(resume_from_checkpoint=ckpt)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/transformers/t
rainer.py", line 2238, in train
    return inner_training_loop(
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/transformers/t
rainer.py", line 2663, in _inner_training_loop 
    self.control = self.callback_handler.on_step_end(args, self.state, self.control)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/transformers/t
rainer_callback.py", line 534, in on_step_end
    return self.call_event("on_step_end", args, state, control)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/transformers/t
rainer_callback.py", line 556, in call_event
    result = getattr(callback, event)(
  File "/home/nick11roberts/github.com/shangshang-wang/Tina/tina/post_train_hf/callback.py",
 line 42, in on_step_end
    completion = self.eval_prompt(model, processing_class)
  File "/home/nick11roberts/github.com/shangshang-wang/Tina/tina/post_train_hf/callback.py",
 line 54, in eval_prompt
    outputs = model.generate(
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/peft/peft_mode
l.py", line 1973, in generate
    outputs = self.base_model.generate(*args, **kwargs)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/utils/_c
ontextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/transformers/g
eneration/utils.py", line 2634, in generate
    result = self._sample(
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/transformers/g
eneration/utils.py", line 3660, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/nick11roberts/github.com/shangshang-wang/Tina/./tina/post_train_hf/gr
po.py", line 264, in <module>
[rank0]:     main()
[rank0]:   File "/home/nick11roberts/github.com/shangshang-wang/Tina/./tina/post_train_hf/gr
po.py", line 252, in main
[rank0]:     train_result = trainer.train(resume_from_checkpoint=ckpt)
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/trans
formers/trainer.py", line 2238, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/trans
formers/trainer.py", line 2663, in _inner_training_loop
[rank0]:     self.control = self.callback_handler.on_step_end(args, self.state, self.control
)
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/trans
formers/trainer_callback.py", line 534, in on_step_end
[rank0]:     return self.call_event("on_step_end", args, state, control)
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/trans
formers/trainer_callback.py", line 556, in call_event
[rank0]:     result = getattr(callback, event)(
[rank0]:   File "/home/nick11roberts/github.com/shangshang-wang/Tina/tina/post_train_hf/call
back.py", line 42, in on_step_end
[rank0]:     completion = self.eval_prompt(model, processing_class)
[rank0]:   File "/home/nick11roberts/github.com/shangshang-wang/Tina/tina/post_train_hf/call
back.py", line 54, in eval_prompt
[rank0]:     outputs = model.generate(
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/peft/
peft_model.py", line 1973, in generate
[rank0]:     outputs = self.base_model.generate(*args, **kwargs)
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch
/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/trans
formers/generation/utils.py", line 2634, in generate
[rank0]:     result = self._sample(
[rank0]:   File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/trans
formers/generation/utils.py", line 3660, in _sample
[rank0]:     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
[rank0]: RuntimeError: CUDA error: device-side assert triggered
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[E814 00:45:41.660907272 ProcessGroupNCCL.cpp:1595] [PG ID 4 PG GUID 7 Rank 0] Proce
ss group watchdog thread terminated with exception: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (mos
t recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7434c5f6c446 in /hom
e/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string co
nst&) + 0x64 (0x7434c5f166e4 in /home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site
-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool)
 + 0x118 (0x7434c63c09f8 in /home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-pac
kages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7
434777b9626 in /home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/l
ib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7434777be2f0 in /home/ni
ck11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7434777c5a5a in /home/nick11r
oberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7434777c751d in /home/nick11
roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7434c643b5c0 in /home/nick11roberts/miniconda3/env
s/tina/lib/python3.10/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x9caa4 (0x7434d8c9caa4 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x129c3c (0x7434d8d29c3c in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 4 PG GUID 7 Rank 0] Process group watchdog thread terminated with exceptio
n: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (mos
t recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7434c5f6c446 in /hom
e/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string co
nst&) + 0x64 (0x7434c5f166e4 in /home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site
-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool)
 + 0x118 (0x7434c63c09f8 in /home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-pac
kages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7
434777b9626 in /home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/l
ib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7434777be2f0 in /home/ni
ck11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7434777c5a5a in /home/nick11r
oberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7434777c751d in /home/nick11
roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x145c0 (0x7434c643b5c0 in /home/nick11roberts/miniconda3/env
s/tina/lib/python3.10/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x9caa4 (0x7434d8c9caa4 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x129c3c (0x7434d8d29c3c in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cp
p:1601 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7434c5f6c446 in /hom
e/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe3f297 (0x74347743f297 in /home/nick11roberts/miniconda3/en
vs/tina/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x145c0 (0x7434c643b5c0 in /home/nick11roberts/miniconda3/env
s/tina/lib/python3.10/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x9caa4 (0x7434d8c9caa4 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x129c3c (0x7434d8d29c3c in /lib/x86_64-linux-gnu/libc.so.6)

E0814 00:45:42.793000 25019 site-packages/torch/distributed/elastic/multiprocessing/api.py:8
69] failed (exitcode: -6) local_rank: 0 (pid: 25105) of binary: /home/nick11roberts/minicond
a3/envs/tina/bin/python3.10
Traceback (most recent call last):
  File "/home/nick11roberts/miniconda3/envs/tina/bin/accelerate", line 7, in <module>
    sys.exit(main())
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/accelerate/com
mands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/accelerate/com
mands/launch.py", line 1220, in launch_command 
    deepspeed_launcher(args)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/accelerate/com
mands/launch.py", line 906, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/distribu
ted/run.py", line 910, in run
    elastic_launch(
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/distribu
ted/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/nick11roberts/miniconda3/envs/tina/lib/python3.10/site-packages/torch/distribu
ted/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
./tina/post_train_hf/grpo.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-14_00:45:42
  host      : mai-tai
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 25105)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 25105
======================================================
END TIME: Thu Aug 14 12:45:43 AM CDT 2025
DONE
```

**Comment by nick11roberts** [comment]
Ah just to add to this, it seems like the crash is aligned with when checkpoints are saved. If I change `save_steps` to 1 and `gradient_accumulation_steps` to 1, it fails on the first step with the same error.

**Comment by shangshang-wang** [comment]
Hey! Nice found on the single GPU setting. Previously Tina's experiments were all on 2-GPU settings so thanks for trying it out on single GPU.

Long story short, the problem is `gradient checkpointing` option in the config yaml, turning that off would make it work on single GPU. The following is the detailed debug process:

> Assertion `probability tensor contains either `inf`, `nan` or element < 0`

I thought this might because the model accidentally generated weird tokens that cause the numerical issue in probability tensor computation. So I looked into configs in `callback.py` like `max_generation_length, temperature, top_k, top_p,` etc. Eventually, I used a test setup where 
1. `system_prompt` is "What is the solution of 1 plus 1?"
2. `max_generation_length` is 256
3. `do_sample=False` is set in the `model.generate` function
All these should make the model to generate much fewer tokens in a greedy manner to lower the probability of generating weird tokens. However, I tested across several random seeds, they all failed.

Then, I started to think about why it works on 2 GPUs and what may fail on 1 GPU. I basically ablated options like `use_vllm`, `vllm_gpu_memory_utilization`, `gradient_checkpointing` and more in the yaml config file. And finally when I turned off the gradient checkpointing, the error shifted from "device-side assert" to "cuda out-of-memory", which is a much easier problem to solve with tweaks on batch size and number of generations in GRPO, etc.

The following config for `Qwen2.5-0.5B` works well without gradient checkpointing on one GPU (on my end, I did NOT get the 1.5B model work on one GPU due to GPU memory even though I tried to lower hyperparameter as possible as I can)

```yaml
# check ./tina/config.py
model_post_train_dataset_name: still
model_post_train_type: grpo
rl_post_train_reward_weights:
- 1.0
- 2.0


# Model configs from trl
model_name_or_path: Qwen2.5-0.5B
attn_implementation: flash_attention_2
use_peft: true
lora_r: 32
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj


# GRPO trainer configs from trl
bf16: true
use_vllm: true
vllm_device: cuda:0
vllm_gpu_memory_utilization: 0.2
vllm_max_model_len: 4608
gradient_accumulation_steps: 4
gradient_checkpointing: false # true
gradient_checkpointing_kwargs:
  use_reentrant: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
push_to_hub: false # set as false on purpose
hub_strategy: every_save
hub_private_repo: true
hub_model_id: upup-ashton-wang # TODO

learning_rate: 1e-06
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 512
max_completion_length: 3584
max_steps: 7500 # use 7500 for lr scheduler but stop at 3750 steps
num_generations: 2
num_train_epochs: 1
overwrite_output_dir: true
per_device_train_batch_size: 2
report_to:
- wandb

save_strategy: steps
save_steps: 1 # 10
save_total_limit: 100

seed: 42
temperature: 0.7
warmup_ratio: 0.1

```

**Comment by nick11roberts** [comment]
Thank you @shangshang-wang! This 0.5B config works for me. Though for the larger 1.5B model, when I disable gradient checkpointing and (just for debugging purposes) set `lora_r: 1`, `max_prompt_length: 128`, and `max_completion_length: 512`, I no longer get a Cuda OOM, but I do get the same error as before. In any case I'll just stick with 0.5B for now -- I plan to switch to another model family next anyway. 

Thanks again!
